
export const Routes = {
    // pages
    Presentation: { path: "/" },
    DashboardOverview: { path: "/dashboard" },
    Transactions: { path: "/transactions" },
    Courses: { path: "/courses" },
    Access: { path: "/access" },
    ProfileSettings: { path: "/profile-settings" },
    GeneralSettings: { path: "/general-settings" },
    ProductItems: { path: "/products" },
    Upgrade: { path: "/upgrade" },
    AllTransactions: { path: "/finance/all" },
    Subscriptions: { path: "/finance/subscriptions" },
    Billing: { path: "/billing" },
    Invoice: { path: "/invoice" },
    Signin: { path: "/sign-in" },
    Signup: { path: "/sign-up" },
    ForgotPassword: { path: "/forgot-password" },
    ResetPassword: { path: "/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/error" },
    ServerError: { path: "/server-error" },
    Docs: { path: "/docs" },
    Support: { path: "/support" },
    Contacts: { path: "/contacts" },

    // users
    Teachers: { path: "/users/teachers" },
    Pupils: { path: "/users/pupils" },
    Parents: { path: "/users/parents" },
    Legals: { path: "/users/legals" },
    Leads: { path: "/users/leads" },

    // docs
    DocsOverview: { path: "/documentation/start" },
    DocsDownload: { path: "/documentation/sections" },
    DocsQuickStart: { path: "/documentation/for-admin" },
    DocsLicense: { path: "/documentation/for-teachers" },
    DocsFolderStructure: { path: "/documentation/for-parents" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};